import type { Project } from "@/shared/types/project";

export const workspaceProjects: Project[] = [
  {
    id: "project-education-site",
    title: "教育品牌官网升级方案",
    clientName: "清林教育",
    clientCompany: "清林教育科技有限公司",
    projectType: "website",
    industry: "教育培训",
    contactName: "周老师",
    contactPhone: "138-0000-2568",
    summary: null,
    background: null,
    goal: null,
    scope: null,
    rawRequirement: null,
    duration: null,
    deliveryNote: null,
    remark: null,
    templateType: "full",
    totalPrice: "38000.00",
    status: "generated",
    shareToken: "share-project-education-site",
    updatedAt: "今天 14:20",
    createdAt: "2026-06-18T10:00:00Z"
  },
  {
    id: "project-mini-program",
    title: "会员小程序二期迭代",
    clientName: "北岸零售",
    clientCompany: "北岸零售科技有限公司",
    projectType: "mini_program",
    industry: "零售",
    contactName: "吴经理",
    contactPhone: "139-1111-7788",
    summary: null,
    background: null,
    goal: null,
    scope: null,
    rawRequirement: null,
    duration: null,
    deliveryNote: null,
    remark: null,
    templateType: "full",
    totalPrice: "56800.00",
    status: "shared",
    shareToken: "share-project-mini-program",
    updatedAt: "今天 10:45",
    createdAt: "2026-06-18T09:30:00Z"
  },
  {
    id: "project-studio-site",
    title: "工作室官网与后台",
    clientName: "造物空间",
    clientCompany: "造物空间工作室",
    projectType: "admin_panel",
    industry: "创意工作室",
    contactName: "李老师",
    contactPhone: "137-2222-9876",
    summary: null,
    background: null,
    goal: null,
    scope: null,
    rawRequirement: null,
    duration: null,
    deliveryNote: null,
    remark: null,
    templateType: "simple",
    totalPrice: "29600.00",
    status: "draft",
    shareToken: null,
    updatedAt: "昨天 18:12",
    createdAt: "2026-06-17T18:12:00Z"
  }
];
